### ISSUE TITLE
Investigate Github Webhooks

### ISSUE THREAD

**Issue by rasmus-d** [KTH-DD2480-Fundsoft/assignment-2#2]
Description: We need to know how our interface with Github will look like. We need to define a clear structure on how webhooks will be handled by our server. We also need to know how to add webhooks in github. We plan on using Flask to handle all the http communication, tailor the structure to Flask.

DoD: A specification which stipulates how webhooks are handled in flask and how webhooks are to be added in Github.

**Comment by sebastianmonten** [comment]
# Server
server.py
```
from flask import Flask, request

app = Flask(__name__)

def extract_basic_info(data):
    repo_name = data.get('repository', {}).get('name', 'Unknown Repo')
    pusher_name = data.get('pusher', {}).get('name', 'Unknown Pusher')
    branch_ref = data.get('ref', 'Unknown Branch')
    return f"Repo: {repo_name}, Pusher: {pusher_name}, Branch: {branch_ref}"

@app.route('/webhook', methods=['POST', 'GET'])
def webhook():
    data = request.json
    basic_info = extract_basic_info(data)
    # Write basic information of the received JSON payload to log.txt, in sub directory for better user access
    with open('/tmp/log.txt', 'a') as f:
        f.write(f"Received webhook payload: {basic_info}\n")
    return 'Webhook received successfully', 200

if __name__ == '__main__':
    app.run(host='0.0.0.0',port=8027)

```
Example: `git push --set-upstream origin test/2/test-webhook` to GitHub results in the following line in `log.txt`: 
`Received webhook payload: Repo: assignment-2, Pusher: sebastianmonten, Branch: refs/heads/test/2/test-webhook`


# GitHub Webhook settings
https://github.com/KTH-DD2480-Fundsoft/assignment-2/settings/hooks
Content type: `application/json`
Which events would you like to trigger this webhook? `Just the push event`

# How to clone and pull a repo on KTH machine from ssh
1. If not automatically added, add ssh credentials for github account to agent
2. in the same dir enter: `ssh -A studentID@student-shell.sys.kth.se` wich brings that into the session

# How to run the server and connect it to the Webhook
1. `python3 server.py`
2. in another terminal window: `ngrok http 8027`
3. copy the link that ngrok prints out, looks like this: `https://b418-78-70-58-69.ngrok-free.app`
4. paste that link with `/webhook` in github webhook setting: `https://b418-78-70-58-69.ngrok-free.app/webhook`

# Suggestion for implementing this on the KTH remote machine
1. `nohup python server.py &` run server without hangups
2. `nohup ngrok http 8027 &` start ngrok tunnel without hangups
3. Login to https://ngrok.com/ and go to CloudEdge -> Endpoints -> Url ( Example :- 7xx-2exx-49xx-e9xx.......in.ngrok.io/) There might two URLs instead of one here, try which one works.
4. paste that link between `https://` and `/webhook` in github webhook setting: `https://b418-78-70-58-69.ngrok-free.app/webhook`

## How to terminate the server and ngrok process
1. Get the PID for ngrok: `ps aux | grep ngrok`and then kill process with `kill -9 23684` where 23684 is the PID
2. Get the PID for python3: `ps aux | grep python3`and then kill process with `kill -9 23684` where 23684 is the PID

**Comment by rasmus-d** [comment]
Great job, we merged the implementation. Closing this.
