### ISSUE TITLE
Add remaining documentation to public API functions

### ISSUE THREAD

**Issue by Stenmarken** [KTH-DD2480-Fundsoft/assignment-2#45]
Definition: It's a requirement for P that all public API functions should be documented. Look at currently documented functions to get the correct structure and style.

Definition of done: All public API functions have a docstring documenting what it's used for, what its parameters are, and what it returns.

Tests: Verify that the documentation generation goes through.

**Comment by dantevi** [comment]
In the PR for this issue, there are many TODOs regarding documentation that need to be resolved. Help is needed with this due to lack of complete understanding of the details of the code that is to be documented .

Namely, the TODOs are in the following files:

- `GitHub_API_functions.py` – 1 TODO
- `ci_runner.py` – 3 TODOs
- `logger.py` – 2 TODOs
- `test_server.py` – 8 TODOs

**Comment by Stenmarken** [comment]
I've solved the TODOs in ci_runner.py, test_server.py and all but one in logger.py I removed the TODOs dealing with the parameters of cls as cls is just a keyword in python.

I was unsure if I could remove the code
```    
    # TODO: This is never used. Can it be removed?
    def filter(self, record):
        return record.levelno == logging.INFO
```
